apiVersion: v1
kind: Service
metadata:
  name: simple-web-app

spec:
  selector:
    app: simple-web-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-web-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: simple-web-app
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: simple-web-app
              servicePort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
        - name: simple-web-app
          image: 915323986442.dkr.ecr.us-west-2.amazonaws.com/simple_node_app:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          

      